name: thememode_selector
description: A widget to select between light and dark ThemeMode (in development, but working fine)
version: 0.1.0-dev.1
repository: https://github.com/BlueCowGroup/thememode_selector
homepage: https://github.com/BlueCowGroup/thememode_selector

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

